### ISSUE TITLE
error upon installing using composer

### ISSUE THREAD

**Issue by christianjosephdalisay** [johnitvn/yii2-ajaxcrud#19]
I tried to install using composer. There seems to have a problem. 
Command: composer update --prefer-dist

Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - johnitvn/yii2-ajaxcrud 1.0.3 requires johnitvn/yii2-ajaxcrud-assets \* -> s
atisfiable by johnitvn/yii2-ajaxcrud-assets[1.0.0, 1.0.1, 1.0.2, 2.0.0, dev-mast
er].
    - johnitvn/yii2-ajaxcrud 1.0.4 requires johnitvn/yii2-ajaxcrud-assets \* -> s
atisfiable by johnitvn/yii2-ajaxcrud-assets[1.0.0, 1.0.1, 1.0.2, 2.0.0, dev-mast
er].
    - johnitvn/yii2-ajaxcrud 1.0.5 requires johnitvn/yii2-ajaxcrud-assets \* -> s
atisfiable by johnitvn/yii2-ajaxcrud-assets[1.0.0, 1.0.1, 1.0.2, 2.0.0, dev-mast
er].
    - johnitvn/yii2-ajaxcrud 1.0.6 requires johnitvn/yii2-ajaxcrud-assets 1.0.*
-> satisfiable by johnitvn/yii2-ajaxcrud-assets[1.0.0, 1.0.1, 1.0.2].
    - johnitvn/yii2-ajaxcrud 2.0.0 requires johnitvn/yii2-ajaxcrud-assets 1.0.*
-> satisfiable by johnitvn/yii2-ajaxcrud-assets[1.0.0, 1.0.1, 1.0.2].
    - johnitvn/yii2-ajaxcrud dev-master requires johnitvn/yii2-ajaxcrud-assets *
 -> satisfiable by johnitvn/yii2-ajaxcrud-assets[1.0.0, 1.0.1, 1.0.2, 2.0.0, dev
-master].
    - johnitvn/yii2-ajaxcrud 2.0.1 requires johnitvn/yii2-ajaxcrud-assets 2.0.*
-> satisfiable by johnitvn/yii2-ajaxcrud-assets[2.0.0].
    - johnitvn/yii2-ajaxcrud 1.0.0 requires kartik-v/yii2-mpdf v1.0.0 -> satisfi
able by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud 1.0.1 requires kartik-v/yii2-mpdf v1.0.0 -> satisfi
able by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud 1.0.2 requires kartik-v/yii2-mpdf v1.0.0 -> satisfi
able by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud-assets 1.0.0 requires kartik-v/yii2-mpdf v1.0.0 ->
satisfiable by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud-assets 1.0.1 requires kartik-v/yii2-mpdf v1.0.0 ->
satisfiable by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud-assets 1.0.2 requires kartik-v/yii2-mpdf v1.0.0 ->
satisfiable by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud-assets 2.0.0 requires kartik-v/yii2-mpdf v1.0.0 ->
satisfiable by kartik-v/yii2-mpdf[v1.0.0].
    - johnitvn/yii2-ajaxcrud-assets dev-master requires kartik-v/yii2-mpdf v1.0.
0 -> satisfiable by kartik-v/yii2-mpdf[v1.0.0].
    - Conclusion: don't install kartik-v/yii2-mpdf v1.0.0
    - Installation request for johnitvn/yii2-ajaxcrud \* -> satisfiable by johnit
vn/yii2-ajaxcrud[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 2.0.0, 2.0.1,
dev-master].

Note. I already installed kartik-v/yii2-mpdf. It's already in its latest release.

**Comment by johnitvn** [comment]
You can reupdate newest version [2.0.2](https://github.com/johnitvn/yii2-ajaxcrud/releases/tag/2.0.2). This bug is fixed now
