### ISSUE TITLE
Class 'johnitvn\ajaxcrudasset\CrudAsset' not found

### ISSUE THREAD

**Issue by drsdre** [johnitvn/yii2-ajaxcrud#21]
After upgrading from 1.0.4 to 2.0.2 through composer, I've not been able to get it up and running anymore. It stops working with the message:
Class 'johnitvn\ajaxcrudassets\CrudAsset' not found

I've created pull request https://github.com/johnitvn/yii2-ajaxcrud/pull/20 with a fix.

**Comment by johnitvn** [comment]
Thanks so much.
