### ISSUE TITLE
Compatibility with kartik/widgets

### ISSUE THREAD

**Issue by christianjosephdalisay** [johnitvn/yii2-ajaxcrud#23]
Your generation of index file was based to kartik gridview. Are the other widgets of kartik compatible with this module? I tried to migrating kartik's widget to yours. I tried select onto the form builder, but it 
 does not load the widget.

![capture](https://cloud.githubusercontent.com/assets/7392803/8770210/7c47c856-2edf-11e5-8e9a-2b697051ce43.PNG)

**Comment by johnitvn** [comment]
You can see in the yii2-ajaxcrud composer 

Ajax Crud dependence 3 kartik-v/\* package folowing below: 
-  "kartik-v/yii2-grid": "3.0.4",
-  "kartik-v/yii2-mpdf": "v1.0.0",
-  "kartik-v/yii2-editable": "1.7.2"

Any other need you define in required section in your composer.json

**Comment by christianjosephdalisay** [comment]
so what I need to do is add the widgets on the composer.json of this extension... and update this extension?? Because I had already installed the widgets in my composer.json

**Comment by johnitvn** [comment]
Oh i think you misunderstand. You already add widget into your composer.json but it not work. Right?

**Comment by christianjosephdalisay** [comment]
yes. I had been using kartik widgets. I tried to migrate my actions and views into this extension.It does not work.

**Comment by johnitvn** [comment]
Yes. Because some widget in kartik widget library is not very flexible. It auto register assets and script.

In this plugin a ajax request will be send when you call an action create, update or some actions else. You register widget in the content of ajax response. So from ajax response you can't register asset for main page. That's reason for widget not work. 

This is a complex problem, so i recommend following below:
1. Request kartik add feature register asset manualy, so you can register asset in index and use widget it in ajax response view
1. You can do it by yourself, you must extends and modified something in kartik-v widgets
2. You can write a new widget

I'm sory because can't help you more

**Comment by zmoddynamics** [comment]
Hi, I have the same problem here. the kartik widgets work fine outside of the ajaxcrud pages. But they don't show up inside of yours.. I think one way to get around the issue is to do a $this->renderAjax('_form'); inside controller but i am unclear how to do that with your extension.

**Comment by zmoddynamics** [comment]
I think I have a solution. Will update shortly..

**Comment by zmoddynamics** [comment]
Hmm... I am really puzzled why changing the return value in actionCreate to this:

return [
                   'title'=> "Create new Promo",
                   'content'=>$this->renderAjax('_form', [
                       'model' => $model,
                   ]),
                   'footer'=> Html::button('Close',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                               Html::button('Save',['class'=>'btn btn-primary','type'=>"submit"])

```
           ];
```

does not solve the problem? Is there a solution..? I've returned kartik widgets from renderAJax before on with my own modals and ajax calls so I don't understand why this isn't working with your widget ?

**Comment by zmoddynamics** [comment]
renderAjax should be registering the kartik widget assets.. Thats the whole point...
http://www.yiiframework.com/doc-2.0/yii-web-view.html#renderAjax()-detail

**Comment by sanjarbek** [comment]
@zmoddynamics related to your last comment it seems you find solution, can you share? How to register kartik widget assets on renderajax?

**Comment by hyquoccuong** [comment]
Here's the solution: In conftroller and middle file we need to use renderAjax

```
return [
                    'title' => "Create new App User",
                    'content' => $this->renderAjax('create', [
                        'model' => $model,
                    ]),
                    'footer' => Html::button('Close', ['class' => 'btn btn-default pull-left', 'data-dismiss' => "modal"]) .
                        Html::button('Save', ['class' => 'btn btn-primary', 'type' => "submit"])
];
```

In create.php

```
<div class="app-user-create">
    <?php if (Yii::$app->request->isAjax) { ?>
        <?= $this->renderAjax('_form', [
            'model' => $model,
        ]) ?>
    <?php } else { ?>
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
    <?php } ?>

</div>
```

And in _form.php (form view) we can use kartik widgets properly

```
<?= $form->field($model, 'country')->widget(\kartik\widgets\Select2::className(), [
        'data' => backend\modules\app\models\AppUser::lookupData('system_country', 'country_name', 'country_name'),
        'options' => [
            'multiple' => false,
            'prompt' => 'Select Country'
        ],
        'pluginOptions' => [
            'allowClear' => true,
            'tags' => true
        ]
    ]) ?>
```
