### ISSUE TITLE
kartik-v/yii2-editable

### ISSUE THREAD

**Issue by zmoddynamics** [johnitvn/yii2-ajaxcrud#24]
Latest version is kartik-v/yii2-editable: 1.7.3 (which includes important updates). Please update this package when you can.

**Comment by zmoddynamics** [comment]
Thanks! 1.7.3 allows inline editable forms. Appreciate the quick response. Great work on the extensions btw.

**Comment by johnitvn** [comment]
You are welcome :)

**Comment by zmoddynamics** [comment]
Hi,

I still have problem:

johnitvn/yii2-rbac-plus 1.0.0 requires johnitvn/yii2-ajaxcrud 2.0.3

Looks like rback-plus 1.0.0 requires johnitvn/yii2-ajaxcrud 2.0.3
The update you applied is valid for yii2-ajaxcrud 2.0.7

Is it possible to update yii2-rbac-plus to use yii2-ajaxcrud 2.0.7 ?

Warm Regards,

Clint Zeringue, Ph.D.
Scientific Programmer/Web Developer
Office: 832.945.5568 file://localhost/tel/832.945.5568
Cell: 657.201.9663 tel:657.201.9663
Skype: clint.zeringue
clint.zeringue@zmoddynamics.com

This email is intended only for the person to whom it is addressed and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of ZModDynamics LLC. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and disseminating
any information related to this email is prohibited, and that you should not
take any action based on the content of this email and/or its attachments.
If you received this message in error, please contact the sender and destroy
all copies of this email and any attachment. Please note that the views and
opinions expressed herein are solely those of the author and do not
necessarily reflect those of the company. While antivirus protection tools
have been employed, you should check this email and attachments for the
presence of viruses. No warranties or assurances are made in relation to the
safety and content of this email and attachments. ZModDynamics LLC accepts
no liability for any damage caused by any virus transmitted by or contained
in this email and attachments. No liability is accepted for any consequences
arising from this email.

 ZModDynamics LLC
28210 Emerald Creek Ln, Fulshear,TX 77441
Tel: 657.201.9663 tel:657.201.9663
zmoddynamics.com http://www.zmoddynamics.com
Facebook https://www.facebook.com/zmoddynamics  | LinkedIn
http://www.linkedin.com/company/2973453  | Twitter
https://twitter.com/ZModDynamics

From:  John Martin notifications@github.com
Reply-To:  johnitvn/yii2-ajaxcrud
<reply+000eb5a5dd685ffaad1a457da4f6fc4d969dab63cb0e393792cf0000000111da275b9
2a169ce05e1a88d@reply.github.com>
Date:  Wednesday, August 5, 2015 at 2:34 PM
To:  johnitvn/yii2-ajaxcrud yii2-ajaxcrud@noreply.github.com
Cc:  "Clint Zeringue,Ph.D." Clint.Zeringue@ZModDynamics.com
Subject:  Re: [yii2-ajaxcrud] kartik-v/yii2-editable (#24)

You are welcome :)



**Comment by johnitvn** [comment]
Yes. It's already update to date
[https://github.com/johnitvn/yii2-rbac-plus/commit/67bec3d8f79d4c560a85fa7588a86e7e4229781c](https://github.com/johnitvn/yii2-rbac-plus/commit/67bec3d8f79d4c560a85fa7588a86e7e4229781c)

Thanks for feedback

**Comment by zmoddynamics** [comment]
Thanks!
Warm Regards,

Clint Zeringue, Ph.D.
Scientific Programmer/Web Developer
Office: 832.945.5568 file://localhost/tel/832.945.5568
Cell: 657.201.9663 tel:657.201.9663
Skype: clint.zeringue
clint.zeringue@zmoddynamics.com

This email is intended only for the person to whom it is addressed and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of ZModDynamics LLC. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and disseminating
any information related to this email is prohibited, and that you should not
take any action based on the content of this email and/or its attachments.
If you received this message in error, please contact the sender and destroy
all copies of this email and any attachment. Please note that the views and
opinions expressed herein are solely those of the author and do not
necessarily reflect those of the company. While antivirus protection tools
have been employed, you should check this email and attachments for the
presence of viruses. No warranties or assurances are made in relation to the
safety and content of this email and attachments. ZModDynamics LLC accepts
no liability for any damage caused by any virus transmitted by or contained
in this email and attachments. No liability is accepted for any consequences
arising from this email.

 ZModDynamics LLC
28210 Emerald Creek Ln, Fulshear,TX 77441
Tel: 657.201.9663 tel:657.201.9663
zmoddynamics.com http://www.zmoddynamics.com
Facebook https://www.facebook.com/zmoddynamics  | LinkedIn
http://www.linkedin.com/company/2973453  | Twitter
https://twitter.com/ZModDynamics

From:  John Martin notifications@github.com
Reply-To:  johnitvn/yii2-ajaxcrud
<reply+000eb5a50c3b582dcf40dc9bfa81b3defe5e6abf11414c4792cf0000000111da61439
2a169ce05e1a88d@reply.github.com>
Date:  Wednesday, August 5, 2015 at 6:41 PM
To:  johnitvn/yii2-ajaxcrud yii2-ajaxcrud@noreply.github.com
Cc:  "Clint Zeringue,Ph.D." Clint.Zeringue@ZModDynamics.com
Subject:  Re: [yii2-ajaxcrud] kartik-v/yii2-editable (#24)

Yes. It's already update to date
johnitvn/yii2-rbac-plus@67bec3d
<https://github.com/johnitvn/yii2-rbac-plus/commit/67bec3d8f79d4c560a85fa758
8a86e7e4229781c> 

Thanks for feedback



**Comment by zmoddynamics** [comment]
You also have some errors in the rbac-plus 1.0.1 module see below:

Static function johnitvn\rbacplus\models\AuthItem::find() should not be
abstract

 public abstract static function find($name);

There was another error that I recall when I first installed this but I
can¹t seem to find it now..

Warm Regards,

Clint Zeringue, Ph.D.
Scientific Programmer/Web Developer
Office: 832.945.5568 file://localhost/tel/832.945.5568
Cell: 657.201.9663 tel:657.201.9663
Skype: clint.zeringue
clint.zeringue@zmoddynamics.com

This email is intended only for the person to whom it is addressed and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of ZModDynamics LLC. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and disseminating
any information related to this email is prohibited, and that you should not
take any action based on the content of this email and/or its attachments.
If you received this message in error, please contact the sender and destroy
all copies of this email and any attachment. Please note that the views and
opinions expressed herein are solely those of the author and do not
necessarily reflect those of the company. While antivirus protection tools
have been employed, you should check this email and attachments for the
presence of viruses. No warranties or assurances are made in relation to the
safety and content of this email and attachments. ZModDynamics LLC accepts
no liability for any damage caused by any virus transmitted by or contained
in this email and attachments. No liability is accepted for any consequences
arising from this email.

 ZModDynamics LLC
28210 Emerald Creek Ln, Fulshear,TX 77441
Tel: 657.201.9663 tel:657.201.9663
zmoddynamics.com http://www.zmoddynamics.com
Facebook https://www.facebook.com/zmoddynamics  | LinkedIn
http://www.linkedin.com/company/2973453  | Twitter
https://twitter.com/ZModDynamics

From:  John Martin notifications@github.com
Reply-To:  johnitvn/yii2-ajaxcrud
<reply+000eb5a50c3b582dcf40dc9bfa81b3defe5e6abf11414c4792cf0000000111da61439
2a169ce05e1a88d@reply.github.com>
Date:  Wednesday, August 5, 2015 at 6:41 PM
To:  johnitvn/yii2-ajaxcrud yii2-ajaxcrud@noreply.github.com
Cc:  "Clint Zeringue,Ph.D." Clint.Zeringue@ZModDynamics.com
Subject:  Re: [yii2-ajaxcrud] kartik-v/yii2-editable (#24)

Yes. It's already update to date
johnitvn/yii2-rbac-plus@67bec3d
<https://github.com/johnitvn/yii2-rbac-plus/commit/67bec3d8f79d4c560a85fa758
8a86e7e4229781c> 

Thanks for feedback



**Comment by johnitvn** [comment]
I have no time to fix it, now. But how to you installed yii2-rbac-plus.
Do you run the migrate database and add authManager component

**Comment by zmoddynamics** [comment]
Yes, It all works. I just edited that file when I first installed this to
fix the issue. But when I updated the package it overwrote my change. I will
go through my notes and find how I modified that file for the fix and get
back with you so you can update the package. Thanks.
Warm Regards,

Clint Zeringue, Ph.D.
Scientific Programmer/Web Developer
Office: 832.945.5568 file://localhost/tel/832.945.5568
Cell: 657.201.9663 tel:657.201.9663
Skype: clint.zeringue
clint.zeringue@zmoddynamics.com

This email is intended only for the person to whom it is addressed and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of ZModDynamics LLC. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and disseminating
any information related to this email is prohibited, and that you should not
take any action based on the content of this email and/or its attachments.
If you received this message in error, please contact the sender and destroy
all copies of this email and any attachment. Please note that the views and
opinions expressed herein are solely those of the author and do not
necessarily reflect those of the company. While antivirus protection tools
have been employed, you should check this email and attachments for the
presence of viruses. No warranties or assurances are made in relation to the
safety and content of this email and attachments. ZModDynamics LLC accepts
no liability for any damage caused by any virus transmitted by or contained
in this email and attachments. No liability is accepted for any consequences
arising from this email.

 ZModDynamics LLC
28210 Emerald Creek Ln, Fulshear,TX 77441
Tel: 657.201.9663 tel:657.201.9663
zmoddynamics.com http://www.zmoddynamics.com
Facebook https://www.facebook.com/zmoddynamics  | LinkedIn
http://www.linkedin.com/company/2973453  | Twitter
https://twitter.com/ZModDynamics

From:  John Martin notifications@github.com
Reply-To:  johnitvn/yii2-ajaxcrud
<reply+000eb5a5f04d6c5f56e226cf76c157e16b230ef82a8e311792cf0000000111da68a69
2a169ce05e1a88d@reply.github.com>
Date:  Wednesday, August 5, 2015 at 7:13 PM
To:  johnitvn/yii2-ajaxcrud yii2-ajaxcrud@noreply.github.com
Cc:  "Clint Zeringue,Ph.D." Clint.Zeringue@ZModDynamics.com
Subject:  Re: [yii2-ajaxcrud] kartik-v/yii2-editable (#24)

I have no time to fix it, now. But how to you installed yii2-rbac-plus.
Do you run the migrate database and add authManager component



**Comment by johnitvn** [comment]
Thank you. And can you create pull request?

**Comment by zmoddynamics** [comment]
Hi John,

Sorry. I am new to git so I don¹t know how to do what you ask. Still
learning itHere are the changes I made which got rid of the strict PHP
Warnings:

johnitvn/yii2-rbac-plus/src/models/AuthItem.php

```
CHANGED FROM: 

public abstract function find($name);

CHANGED TO:

public static function find($name) {
    return;
}
```

johnitvn/yii2-rbac-plus/src/models/AuthItem.php

   CHANGED FROM: 

   public function afterSave() {

   }

  CHANGED TO:

   public function afterSave($insert) {

   }

Warm Regards,

Clint Zeringue, Ph.D.
Scientific Programmer/Web Developer
Office: 832.945.5568 file://localhost/tel/832.945.5568
Cell: 657.201.9663 tel:657.201.9663
Skype: clint.zeringue
clint.zeringue@zmoddynamics.com

This email is intended only for the person to whom it is addressed and/or
otherwise authorized personnel. The information contained herein and
attached is confidential and the property of ZModDynamics LLC. If you are
not the intended recipient, please be advised that viewing this message and
any attachments, as well as copying, forwarding, printing, and disseminating
any information related to this email is prohibited, and that you should not
take any action based on the content of this email and/or its attachments.
If you received this message in error, please contact the sender and destroy
all copies of this email and any attachment. Please note that the views and
opinions expressed herein are solely those of the author and do not
necessarily reflect those of the company. While antivirus protection tools
have been employed, you should check this email and attachments for the
presence of viruses. No warranties or assurances are made in relation to the
safety and content of this email and attachments. ZModDynamics LLC accepts
no liability for any damage caused by any virus transmitted by or contained
in this email and attachments. No liability is accepted for any consequences
arising from this email.

 ZModDynamics LLC
28210 Emerald Creek Ln, Fulshear,TX 77441
Tel: 657.201.9663 tel:657.201.9663
zmoddynamics.com http://www.zmoddynamics.com
Facebook https://www.facebook.com/zmoddynamics  | LinkedIn
http://www.linkedin.com/company/2973453  | Twitter
https://twitter.com/ZModDynamics

From:  John Martin notifications@github.com
Reply-To:  johnitvn/yii2-ajaxcrud
<reply+000eb5a5ce82d4e168733b0a06af406aca8093634b11508b92cf0000000111da6bc69
2a169ce05e1a88d@reply.github.com>
Date:  Wednesday, August 5, 2015 at 7:26 PM
To:  johnitvn/yii2-ajaxcrud yii2-ajaxcrud@noreply.github.com
Cc:  "Clint Zeringue,Ph.D." Clint.Zeringue@ZModDynamics.com
Subject:  Re: [yii2-ajaxcrud] kartik-v/yii2-editable (#24)

Thank you. And can you create pull request?



**Comment by johnitvn** [comment]
I have been fix it. Can you check for me?
