### ISSUE TITLE
Datepicker widget

### ISSUE THREAD

**Issue by amorev** [johnitvn/yii2-ajaxcrud#25]
Hallo! Thanks you for you extension. I found a bug:

If I add datepicker in filter for some field it will work only for first selection. In connected with calling this line of code:
`$('#contractsearch-datedoc').datepicker($.extend({}, $.datepicker.regional['ru'], {"dateFormat":"yy-mm-dd"}));`

this line is called on page load. But it must be called every time when content in crud is updated (this line makes datepicker work). 

Sorry for my english:)

**Comment by johnitvn** [comment]
Yes. Because content of datatable is load with pjax so you can use

``` javascript
function initDatePicker(){
    $('#contractsearch-datedoc').datepicker($.extend({}, $.datepicker.regional['ru'], {"dateFormat":"yy-mm-dd"}));
}
$(document).on('pjax:complete', initDatePicker);
$(document).on('ready',initDatePicker);
```

**Comment by amorev** [comment]
Thank you very much! 

But i found more universal solutition my adding this:
`'options'=>['class'=>'isDatePicker'],`
in grid-view columns in datepicker calling
and this:
`function initDatePicker() {
    $('.isDatePicker').datepicker(
        $.extend({},
        $.datepicker.regional['ru'], {"dateFormat":"yy-mm-dd"}
        )
        );
}
$(document).on('pjax:complete', initDatePicker);`

in my app.js. Now it works correctly.

**Comment by johnitvn** [comment]
You are welcome

**Comment by amorev** [comment]
But what about form in modals? What event is called on modal window open? I need to initialize datepicker where too. Thanks

**Comment by amorev** [comment]
found a solution by adding 
`initDatePicker()` in view file.

**Comment by tuancode** [comment]
Hi, I use Kartik datepicker widget, and it didn't work with your ajax-crud modal. Should I have add any extra code ? I try use the above solution, but it still didn't work. Please help me!

**Comment by amorev** [comment]
Change $this->renderPartial() to $this->renderAjax() in your controllers and it will work fine) Good Luck!

**Comment by tuancode** [comment]
Thank you very much, it worked perfectly! :+1:

**Comment by amorev** [comment]
I think this fix should be included in repo
