### ISSUE TITLE
Update composer.json to 

### ISSUE THREAD

**Issue by zmoddynamics** [johnitvn/yii2-ajaxcrud#32]
Can you update the requirement to allow kartik-v/yii2-grid  >3.04 ? 
your latest version of this extension 
requires kartik-v/yii2-grid 3.0.4

**Comment by iridance** [comment]
maybe composer.json in some version has wrong

i try to get latest version is ok

you can try this command:

php composer.phar require --prefer-dist johnitvn/yii2-ajaxcrud:2.0.7
