### ISSUE TITLE
1.0.3 version not stable package found

### ISSUE THREAD

**Issue by fedemotta** [johnitvn/yii2-ajaxcrud#5]
Hi,
After separating the code into a different repo, the yii2-ajaxcrud-assets has no stable release, so it is not possible to install yii2-ajaxcrud v1.0.3 because this dependency.

Also: 
Why are you separating those assets in a different repo?

Thanks

**Comment by johnitvn** [comment]
I have create a release version of yii2-ajaxcrud-assets. 

For your question: because in some my other plugin. I did use yii2-ajaxcrud for create the crud. And when some one install that application may be them don't want to use yii2-ajaxcrud. So them need a
separate asset for run
