### ISSUE TITLE
Class 'johnitvn\ajaxcrud\assets\CrudAsset' not found

### ISSUE THREAD

**Issue by hdushku** [johnitvn/yii2-ajaxcrud#6]
after update to version 1.0.3

Class 'johnitvn\ajaxcrud\assets\CrudAsset' not found

**Comment by johnitvn** [comment]
I did separate assets into other repo so you must regenerate or change below line

``` php
use johnitvn\ajaxcrud\assets\CrudAsset;
```

to

``` php
use johnitvn\ajaxcrudassets\CrudAsset; 
```

in index.php

**Comment by hdushku** [comment]
Thanks
Solved
