### ISSUE TITLE
Kartik widgets still use Bootstrap 3

### ISSUE THREAD

**Issue by WinterSilence** [johnitvn/yii2-ajaxcrud#94]
Update code and remove fake version 3.0 from readme

**Comment by Er-Kalpesh** [comment]
please can you review it again and please point me place exactly

**Comment by WinterSilence** [comment]
@Er-Kalpesh don't understand you

**Comment by Er-Kalpesh** [comment]
I think we already removed that version, is there any else with the same? @WinterSilence

**Comment by WinterSilence** [comment]
@Er-Kalpesh you mean yii2-ajaxcrud 3.0? no
Also, need update:
- view `default/controller.php`: use `$this->request`, `$this->asJson()`, in `actionBulkdelete()` use `<?=$modelClass?>::findAll($pks)`
- `src/Bootstrap.php` must be convert to module:
~~~php
class AjaxCrudModule extends \yii\base\Module implements BootstrapInterface
{
    /**
     * Bootstrap method to be called during application bootstrap stage.
     *
     * @param \yii\web\Application $app the application currently running
     */
    public function bootstrap($app)
    {
        Yii::setAlias("@ensostudio", __DIR__);
        Yii::setAlias("@ensostudio/ajaxcrud", __DIR__);
        if ($app->hasModule('gii')) {
            $app->getModule('gii')->generators['ajaxcrud'] = Generator::class;
        }
    }
}
~~~

**Comment by BakhodirIsmatov** [comment]
![image](https://user-images.githubusercontent.com/17880294/147657568-63fdc3f6-ef75-4e40-a78c-390a21581815.png)
please delete this depends
